import { NextPage, Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About | Shop App',
  description: 'Generated by next app',
}

const About: NextPage = () => {
  return <h3>Select subitem</h3>
}

export default About;